name: C/C++ CI with Specific Compiler Versions

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential software-properties-common

    - name: Install GCC 12.3.0
      run: |
        # Add commands to install GCC 12.3.0
        # This might involve adding a PPA, downloading the GCC source, and compiling it

    - name: Install LLVM/Clang/LLD/LLDB 16.0.4
      run: |
        # Add commands to install LLVM/Clang/LLD/LLDB 16.0.4
        # This might involve adding a repository or downloading and compiling from source

    - name: Install MinGW-w64 11.0.0 (UCRT)
      run: |
        # Add commands to install MinGW-w64 11.0.0 (UCRT)
        # This might involve downloading and installing from a specific source

    - name: Compile C/C++ code
      run: |
        gcc --version
        clang --version
        # Replace the following commands with your actual build commands
        gcc *.c -o main 
        # g++ -o main Main.cpp
        # clang -o main Main.c
        # clang++ -o main Main.cpp
      working-directory: /home/runner/work/CPP-Programming/Assignments/Ex3

    - name: Run program
      run: ./main > output.txt
      working-directory: /home/runner/work/CPP-Programming/Assignments/Ex3

    - name: Check output
      run: |
        if grep -q "Hello World" output.txt; then
          echo "Program output is correct"
          exit 0
        else
          echo "Program output is incorrect"
          exit 1
        fi
      working-directory: /home/runner/work/CPP-Programming/Assignments/Ex3