name: C/C++ CI

on: [push, pull_request]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up C/C++ environment
      uses: actions/setup-cpp@v1

    - name: Change to Assignment Directory
      run: cd Assignments/Ex3

    - name: Compile C/C++ code
      run: |
        gcc -o main *.c
        # Or use g++ for C++ files: g++ -o main Main.cpp
      working-directory: Assignments/Ex3

    - name: Run program
      run: ./main > output.txt
      working-directory: Assignments/Ex3

    - name: Check output
      run: |
        if grep -q "Hello World" output.txt; then
          echo "Program output is correct"
          exit 0
        else
          echo "Program output is incorrect"
          exit 1
        fi
      working-directory: Assignments/Ex3