name: C/C++ CI with Specific Compiler Versions

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults: 
      run:
        working-directory: ./Assignments

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential software-properties-common

    # - name: Install GCC 12.3.0
    #   run: |
    #     # Add commands to install GCC 12.3.0
    #     # This might involve adding a PPA, downloading the GCC source, and compiling it

    - name: Compile C/C++ code
      run: |
        gcc --version
        clang --version
        # Replace the following commands with your actual build commands
        gcc *.c -o main 
        # g++ -o main Main.cpp
        # clang -o main Main.c
        # clang++ -o main Main.cpp

    - name: Run program
      run: |
        ./main > output.txt
        cat output.txt

    - name: Check output
      run: |
        if grep -q "^Hello World$" output.txt; then
          echo "Program output is correct"
          exit 0
        else
          echo "Program output is incorrect"
          exit 1
        fi